apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-api-user
  name: udagram-api-user
spec:
  selector:
    matchLabels:
      service: udagram-api-user
  replicas: 2
  template:
    metadata:
      labels:
        service: udagram-api-user
    spec:
      containers:
      - image: unplugged001/udagram-api-user
        name: udagram-api-user
        env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: myconfig
              key: URL
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: myconfig
              key: AWS_BUCKET
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: myconfig
              key: AWS_PROFILE
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: myconfig
              key: AWS_REGION
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: myconfig
              key: JWT_SECRET
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: myconfig
              key: POSTGRESS_DB
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: myconfig
              key: POSTGRES_HOST
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secretsconfig
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: secretsconfig
              key: POSTGRES_USERNAME
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws/"
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: aws-secret
        secret:
          secretName: awssecrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-api-feed
  name: udagram-api-feed
spec:
  selector:
    matchLabels:
      service: udagram-api-feed
  replicas: 2
  template:
    metadata:
      labels:
        service: udagram-api-feed
    spec:
      containers:
      - image: unplugged001/udagram-api-feed
        name: udagram-api-feed
        env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: myconfig
              key: URL
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: myconfig
              key: AWS_BUCKET
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: myconfig
              key: AWS_PROFILE
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: myconfig
              key: AWS_REGION
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: myconfig
              key: JWT_SECRET
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: myconfig
              key: POSTGRESS_DB
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: myconfig
              key: POSTGRES_HOST
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secretsconfig
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: secretsconfig
              key: POSTGRES_USERNAME
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws/"
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: aws-secret
        secret:
          secretName: awssecrets
          
          