apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: reverseproxy
  name: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reverseproxy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: reverseproxy
    spec:
      containers:
      - image: unplugged001/reverseproxy
        name: reverseproxy
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"